# Section headers refer to the *number* of arguments. This means that
# bigrams includes both actual bigrams and skipgrams.
[bigrams]
"Same-finger Bigrams" = { function = "same-finger?", input = "Bigram" }
"Same-finger Repeats" = { function = "same-finger-repeat?", input = "Bigram" }
"Same-finger Skipgrams" = { function = "same-finger?", input = "Skipgram" }
"Same-finger Bigram Distance" = { function = "same-finger-distance", input = "Bigram" }
"Same-finger Skipgram Distance" = { function = "same-finger-distance", input = "Skipgram" }

[trigrams]
