# Section headers refer to the *number* of arguments. This means that
# bigrams includes both actual bigrams and skipgrams.
[bigrams]
"sfb" = { function = "same-finger?", input = "Bigram" }
"sfr" = { function = "same-finger-repeat?", input = "Bigram" }
"sfs" = { function = "same-finger?", input = "Skipgram" }
"sfb distance" = { function = "same-finger-distance", input = "Bigram" }
"sfs distance" = { function = "same-finger-distance", input = "Skipgram" }

[trigrams]
"alternation" = { function = "alternate?", input = "Trigram" }
"redirects" = { function = "redirect?", input = "Trigram" } 
