# Section headers refer to the *number* of arguments. This means that
# bigrams includes both actual bigrams and skipgrams.
[bigrams]
"Same-finger Bigrams" = { function = "sfb?", input = "Bigram"}
"Lateral-stretch Bigrams" = { function = "lsb?", input = "Bigram"}

[trigrams]
